### ISSUE TITLE
peewee >= 3.12.0 needed

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/chimedb#25]
peewee 3.12.0 added `Database.is_connection_usable()`, which is used in `connectdb.py:455`.

```
Traceback (most recent call last):
  File "/scratch/rickn/daily_profiling/venv/code/caput/caput/scripts/runner.py", line 430, in <module>
    cli()
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/rpp-krs/chime/chime_env/modules/chime/python/2020.02/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/scratch/rickn/daily_profiling/venv/code/caput/caput/scripts/runner.py", line 148, in run
    P.run()
  File "/scratch/rickn/daily_profiling/venv/code/caput/caput/pipeline.py", line 603, in run
    out = task._pipeline_next()
  File "/scratch/rickn/daily_profiling/venv/code/caput/caput/pipeline.py", line 1023, in _pipeline_next
    out = self.setup(*tuple(self._requires))
  File "/scratch/rickn/daily_profiling/venv/code/ch-pipeline/ch_pipeline/core/dataquery.py", line 168, in setup
    f = finder.Finder(node_spoof=self.node_spoof)
  File "/scratch/rickn/daily_profiling/venv/code/ch-util/ch_util/finder.py", line 250, in __init__
    connect_database()
  File "/scratch/rickn/daily_profiling/venv/code/ch-util/ch_util/_db_tables.py", line 163, in connect_peewee_tables
    chimedb.core.connect(read_write, reconnect)
  File "/scratch/rickn/daily_profiling/venv/code/chimedb/chimedb/core/orm.py", line 318, in connect_database
    pw_database = connector.get_peewee_database()
  File "/scratch/rickn/daily_profiling/venv/code/chimedb/chimedb/core/connectdb.py", line 455, in get_peewee_database
    if self._database is None or not self._database.is_connection_usable():
AttributeError: 'MySQLDatabaseReconnect' object has no attribute 'is_connection_usable'
```

**Comment by ketiltrout** [comment]
A-ha: https://github.com/chime-experiment/chimedb/pull/24
