### ISSUE TITLE
`mysql-connector-python` Bytearray type not handed properly

### ISSUE THREAD

**Issue by ljgray** [chime-experiment/chimedb#31]
Issue: user name query returns a string in format `str(bytearray(b'...))`, i.e., the resulting string in `"bytearray(b'...')"`.

The following snippet shows this behaviour:
 ```python
    for user_id in MediaWikiUser.select(MediaWikiUser.user_id):
        user_name = (
            MediaWikiUser.select(MediaWikiUser.user_name)
            .where(MediaWikiUser.user_id == user_id)
            .get()
            .user_name
        )
```
where the resulting variable `user_name` will be 
```python 
"bytearray(b'Liam)" 
``` 
for example

**Comment by ljgray** [comment]
Clearly it isn't really breaking anything for us at the moment, I only noticed it because bondia displays user names in a table and they were all in the format that this is returning. Confirmed that it is the output of this query and not something else in bondia though.

**Comment by jrs65** [comment]
I can't reproduce this on my laptop using the old `mysqlclient` based code, but can on cedar where I'm using the new `mysql-connector-python` code.

Here's a quicker producer of it:
```python
>>> list(MediaWikiUser.select(MediaWikiUser.user_id, MediaWikiUser.user_name).limit(5).tuples())
[(298, "bytearray(b'Abhinav96t')"),
 (148, "bytearray(b'Abuenco')"),
 (331, "bytearray(b'Acassity')"),
 (276, "bytearray(b'Acohn')"),
 (261, "bytearray(b'Adaeze.ibik')")]
```

It's probably related to this: https://github.com/mysql/mysql-connector-python/blob/master/CHANGES.txt#L63

**Comment by jrs65** [comment]
We had some other problems with version 8.0.30 (hence the pinning to versions <= 8.0.29), but now there is a new release 8.0.31 so we should probably test that.

**Comment by ljgray** [comment]
Without changing anything else, 8.0.31 does not seem to work.
```
Oct 27 11:38:51 syzygy systemd[1]: bondia.service: Failed with result 'exit-code'.
Oct 27 11:38:51 syzygy systemd[1]: bondia.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 11:38:50 syzygy bondia-server[10980]: chimedb.core.exceptions.ConnectionError: Connection data found, but no connection could be established.
Oct 27 11:38:50 syzygy bondia-server[10980]:     raise ConnectionError(
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/chimedb/core/connectdb.py", line 773, in connect
Oct 27 11:38:50 syzygy bondia-server[10980]:     connectdb.connect(reconnect)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/chimedb/core/orm.py", line 299, in connect_database
Oct 27 11:38:50 syzygy bondia-server[10980]:     chimedb_connect(reconnect=True, read_write=True)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/bin/bondia-server", line 82, in start
Oct 27 11:38:50 syzygy bondia-server[10980]:     return __callback(*args, **kwargs)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/click/core.py", line 760, in invoke
Oct 27 11:38:50 syzygy bondia-server[10980]:     return ctx.invoke(self.callback, **ctx.params)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Oct 27 11:38:50 syzygy bondia-server[10980]:     rv = self.invoke(ctx)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/click/core.py", line 1055, in main
Oct 27 11:38:50 syzygy bondia-server[10980]:     return self.main(*args, **kwargs)
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Oct 27 11:38:50 syzygy bondia-server[10980]:     start()
Oct 27 11:38:50 syzygy bondia-server[10980]:   File "/opt/venvs/bondia/bin/bondia-server", line 120, in <module>
Oct 27 11:38:50 syzygy bondia-server[10980]: Traceback (most recent call last):
Oct 27 11:38:50 syzygy bondia-server[10980]: WARNING:chimedb:Could not establish connection to CHIME database.
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:chimedb:Unable to connect to MySQL database at bao.chimenet.ca port 3307 tunnelled through bao.chimenet.ca to localhost defined by chimedb.config: Could not tunnel through bao.chimenet.ca.
Oct 27 11:38:50 syzygy bondia-server[10980]: ERROR:sshtunnel.SSHTunnelForwarder:Could not open connection to gateway
Oct 27 11:38:50 syzygy bondia-server[10980]: 2022-10-27 11:38:50,802| ERROR   | Could not open connection to gateway
Oct 27 11:38:50 syzygy bondia-server[10980]: INFO:paramiko.transport:Authentication (publickey) failed.
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:paramiko.transport:Agreed upon 'rsa-sha2-512' pubkey algorithm
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:paramiko.transport:Server-side algorithm list: ['ssh-ed25519', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521']
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
Oct 27 11:38:50 syzygy bondia-server[10980]: DEBUG:paramiko.transport:userauth is OK
```
